CREATE TABLE users (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    surname varchar(50) NOT NULL,
    username varchar(50) NOT NULL,
    password varchar(250) NOT NULL,
    role varchar(50),
    yearOfBirth int NOT NULL
);